### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Arhs99** [SEDenmarkLab/Lucid_Somnambulist#17]
Hi, it would be nice to add some instructions or a simple example of how to make a prediction, otherwise this work is useless, thank you

**Comment by zackees** [comment]
lol i know right?

I'm trying to figure it out too and will report what i find.

**Comment by eunjaeshim** [comment]
The conda environment should be updated such that it includes TF and keras.
I can't run the example listed in workflows/add.py with error arising from `DATA = pd.read_hdf(stream_data)`

**Comment by ianrinehart** [comment]
This repo is still under development - there is a command line interface that is still being beta tested right now. The documentation is on its way.

**Comment by ianrinehart** [comment]
@eunjaeshim the conda environment does include TF and keras. See somn.yml, which includes a pip installation of tensorflow (which comes with keras as of TF2).

**Comment by ianrinehart** [comment]
@zackees This repo is under development, and as the Readme says, documentation about quickstart is on its way. 

I am the sole developer of this work, and I have not had time to work on this for a couple of weeks. When the updated documentation is included, I'll put a note here.

**Comment by ianrinehart** [comment]
@Arhs99 OK, understood. 

This repo is under development, and a "quickstart" is on its way.

**Comment by zackees** [comment]
@ianrinehart

You might want to check out the install script I've created for Ubuntu. It's one line:

```
curl -sSL https://raw.githubusercontent.com/zackees/Lucid_Somnambulist/main/install.sh | bash
```

You should copy this to your repo. It will allow more developers to come on board. I've also gone ahead and pinned your dependencies so that a change to `molli_firstgen` won't break the install.

**Comment by zackees** [comment]
Here is a pull request:

https://github.com/SEDenmarkLab/Lucid_Somnambulist/pull/20

**Comment by tutuxiong2024** [comment]
hi, we are interested in your wonderful work, that would be great if you could update a user guide
thanks a lot

**Comment by ianrinehart** [comment]
Installation instructions added, and a container image has been created for easier deployment. See the docker container registry image ianrinehart/somn:1.0 at https://hub.docker.com/repository/docker/ianrinehart/somn/general.
